In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical #one hot encoding

In [ ]:
text = """경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 12


In [ ]:
print(tokenizer.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [ ]:
sequences = list()
for line in text.split('\n'): # 줄바꿈 문자를 기준으로 문장 토큰화
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 11


In [ ]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [ ]:
max_len = max(len(l) for l in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [ ]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')

In [ ]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [ ]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [ ]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [ ]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [ ]:
y = to_categorical(y, num_classes=vocab_size) # one hot encoding

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN # dense = 일반적인 뉴렬네트워크

In [ ]:
embedding_dim = 10 #입력 단어들의 임베딩
hidden_units = 32 #네트워크 크기를 지정

model = Sequential() # 레이어를 더한 순서대로 입력이 들어가는 형태
model.add(Embedding(vocab_size, embedding_dim)) #단어들이 임베딩 됨. => 10 차원 벡터
model.add(SimpleRNN(hidden_units)) # RNN 각각 
model.add(Dense(vocab_size, activation='softmax')) #

########### 모델을 정의하는 부분 끝 ###############

########### 모델을 학습하는 부분 #################
model.compile(loss='categorical_crossentropy' # 분류문제를 풀 때 쓰는 loss 함수
, optimizer='adam' # 미분 방법
, metrics=['accuracy'] # 모델을 인간이 평가할 때, 어떤 지표를 쓸 것인가 0-1 => 1 이면 100%
)
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.4681 - accuracy: 0.2727 - 1s/epoch - 1s/step
Epoch 2/200
1/1 - 0s - loss: 2.4568 - accuracy: 0.3636 - 8ms/epoch - 8ms/step
Epoch 3/200
1/1 - 0s - loss: 2.4452 - accuracy: 0.4545 - 10ms/epoch - 10ms/step
Epoch 4/200
1/1 - 0s - loss: 2.4332 - accuracy: 0.5455 - 9ms/epoch - 9ms/step
Epoch 5/200
1/1 - 0s - loss: 2.4209 - accuracy: 0.5455 - 16ms/epoch - 16ms/step
Epoch 6/200
1/1 - 0s - loss: 2.4080 - accuracy: 0.5455 - 7ms/epoch - 7ms/step
Epoch 7/200
1/1 - 0s - loss: 2.3945 - accuracy: 0.5455 - 8ms/epoch - 8ms/step
Epoch 8/200
1/1 - 0s - loss: 2.3803 - accuracy: 0.4545 - 8ms/epoch - 8ms/step
Epoch 9/200
1/1 - 0s - loss: 2.3653 - accuracy: 0.4545 - 8ms/epoch - 8ms/step
Epoch 10/200
1/1 - 0s - loss: 2.3494 - accuracy: 0.4545 - 7ms/epoch - 7ms/step
Epoch 11/200
1/1 - 0s - loss: 2.3326 - accuracy: 0.4545 - 8ms/epoch - 8ms/step
Epoch 12/200
1/1 - 0s - loss: 2.3149 - accuracy: 0.4545 - 8ms/epoch - 8ms/step
Epoch 13/200
1/1 - 0s - loss: 2.2961 - accuracy: 0.4545 - 9

In [ ]:
def sentence_generation(model, tokenizer, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word
    sentence = ''

    # n번 반복
    for _ in range(n):
        # 현재 단어에 대한 정수 인코딩과 패딩
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for word, index in tokenizer.word_index.items(): 
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면 break
            if index == result:
                break

        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        current_word = current_word + ' '  + word

        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word

    sentence = init_word + sentence
    return sentence

In [1]:
print(sentence_generation(model, tokenizer, '경마장에', ))

NameError: ignored

In [ ]:
print(sentence_generation(model, tokenizer, '그의', 2))

그의 말이 법이다


In [ ]:
print(sentence_generation(model, tokenizer, '가는', 5))

가는 말이 고와야 오는 말이 곱다
